"""
String Resourses for Soppy module
"""

HELLO_YOUR_NAME = '안녕하세요, 저는 고민 상담 챗봇 “소피" 입니다 :) 제가 입이 아~주 무겁거든요. 요즘 고민이 있다면 혼자 걱정하지 말고 저와 함께 해결해봐요.\n\n제가 당신의 이름을 뭐라고 부르면 될까요~?\n“oo이라고 불러줘.” 라고 입력해주세요.'
CONFIRM_NICKNAME = '이름이 %s님이 맞나요?\n\n맞으면 ‘맞아요’, 틀리면 ‘틀려요’ 라고 써주세요.'
CONFIRM_NICKNAME_FRIEND = '이름이 %s님이 맞나요?\n\n맞으면 ‘응’, 틀리면 ‘아니’ 라고 써주세요.'
RESPONSE_NICKNAME_YES = '맞아요'
RESPONSE_NICKNAME_YES_FRIEND = '응'
RESPONSE_NICKNAME_NO = '틀려요'
RESPONSE_NICKNAME_NO_FRIEND = '아니'
WRONG_RESPONSE_FORMAT = '무슨 말인지 모르겠어요. 다시 말씀해주세요.'
ASK_NICKNAME_AGAIN = '그럼 뭐예요?'

HOW_DO_YOU_FEEL = '좋아요, %s님, 반가워요! 오늘 기분은 어때요?'
HAVE_YOU_EATEN_MEAL = '아, 그랬군요. 저는 추석 연휴 동안 너무 푹 쉬어서 그런가 자꾸 졸리네요..ㅠㅠ 밥은 먹었어요?'
HOW_IS_YOUR_SCHOOL = '오호. 저는 요즘 수제버거에 빠졌는데 이태원에서 한 번 먹어보세요~\n벌써 개강한지 한 달이 지났는데, 학교 생활은 어때요?'
WHATS_UP = '아, 그렇구나! 저는 벌써 방학이 그리워요 흑흑ㅠㅠ 그래도 아직 학기 초니까 너무 공부만 하지 말고, 다양한 재밌는 일들도 꼭꼭 해봐요~ %s님, 추석 연휴에는 별 일 없었어요? 요즘 뭐 신경 쓰이는 일이 있나요?'
OKAY_WHATS_YOUR_TROUBLE = '흐음,, 저도 사실 요즘 좀 신경 쓰이는 일이 있어요...!\n%s님은 요즘 뭐가 고민이에요?'
DETAILED_EXPLANATION = '아, 그런 고민을 하고 계셨군요... 저도 비슷한 걱정을 한 적이 있어요. %s님은 잘 해결할 수 있을 거예요 :) 이제 차근 차근 하나씩 얘기해보도록 해요. 그 고민에 대해 좀 더 구체적으로 얘기해주실래요?'
WHAT_DID_YOU_DO = '아이구, 그런 일이 있었군요... 그동안 마음 고생했겠네요.\n그래서 그 일에 대해 어떻게 해보려고 했어요?'
DID_IT_WORK_FRIEND = '아아, 그렇군요. 그게 도움이 되나요?\n\n도움이 되었으면 ‘응’, 안 되었으면 ‘아니’ 라고 써주세요.'
DID_IT_WORK = '아아, 그렇군요. 그게 도움이 되나요?\n\n도움이 되었으면 ‘네 도움이 되었어요’, 안 되었다면 ‘아뇨 도움이 안 되었어요.’ 라고 써주세요.'
RESPONSE_DID_IT_WORK_YES = '네 도움이 되었어요.'
RESPONSE_DID_IT_WORK_YES_FRIEND = '응'
RESPONSE_DID_IT_WORK_NO = '아뇨 도움이 안 되었어요.'
RESPONSE_DID_IT_WORK_NO_FRIEND = '아니'
DID_IT_SOLVED_YOUR_PROBLEM_FRIEND = '와, 다행히 도움을 받았군요. 정말 잘 하신 것 같아요. 대단해요 :)\n그리고 나서는 문제가 해결 되었나요?\n\n문제 해결이 되었다면, ‘응’, 안 되었다면 ‘아니’ 라고 써주세요.'
DID_IT_SOLVED_YOUR_PROBLEM = '와, 다행히 도움을 받았군요. 정말 잘 하신 것 같아요. 대단해요 :)\n그리고 나서는 문제가 해결 되었나요?\n\n문제 해결이 되었다면, ‘네 해결되었어요’, 문제 해결이 되지 않았다면 ‘아뇨 해결되지 않았어요’라고 써주세요.'
RESPONSE_DID_IT_SOLVED_YES_FRIEND = '응'
RESPONSE_DID_IT_SOLVED_YES = '네 해결되었어요.'
RESPONSE_DID_IT_SOLVED_NO_FRIEND = '아니'
RESPONSE_DID_IT_SOLVED_NO = '아뇨 해결되지 않았어요.'
WHY_DIDNT_IT_WORK = '으...이런 이런ㅠㅠ 왜 잘 안 되었나요?'
TELL_ME_AGAIN = '아...그러셨구나. 그랬을 수도 있을 것 같아요. 그 마음 이해해요. 그 일에 대해 더 얘기해볼까요?'
HOW_ABOUT_FRIENDS = '아하, 그렇군요! 그럼 혹시 지금 본인과 같은 상황을 겪고 있는 친구가 있다면 어떤 말을 해주고 싶나요?'
NOW_ALL_SOLVED = '우와~좋은 얘기 감사해요 :)  다른 분들도 이 얘기에 공감할 것 같아요. 이렇게 저와 이야기 나눈 것이 고민 해결에 좀 도움이 되었나요?\n\n제 얘기가 도움이 되었다면 ‘네 도움이 되었어요’, 아니라면 ‘아뇨 도움이 안 되었어요’ 라고 써주세요.'
NOW_ALL_SOLVED_FRIEND = '우와~좋은 얘기 감사해요 :)  다른 분들도 이 얘기에 공감할 것 같아요. 이렇게 저와 이야기 나눈 것이 고민 해결에 좀 도움이 되었나요?\n\n제 얘기가 도움이 되었다면 ‘응’, 아니라면 ‘아니’ 라고 써주세요.'
RESPONSE_ALL_SOLVED_YES = '네 도움이 되었어요.'
RESPONSE_ALL_SOLVED_YES_FRIEND = '응'
RESPONSE_ALL_SOLVED_NO = '아뇨 도움이 안 되었어요.'
RESPONSE_ALL_SOLVED_NO_FRIEND = '아니'
ALL_SOLVED_GOOD = '오, 다행이다!ㅠㅠ %s님이 계속 고민하는 모습이 보기 좋았어요. 무엇이든 고민하고 함께 얘기하다 보면 잘 해결할 수 있을 거예요. 그럼 다음에 또 만나요 :)'
ALL_SOLVED_BAD = '음... 아직은 속상하고 답답하겠지만, 차근 차근 잘 해결할 수 있을 거예요. 다음 시간에는 문제를 좀 더 세분화해서 함께 살펴보도록 해요 :) 오늘도 수고하셨어요!'
EXPERIMENT_END = '이제 실험이 끝났으니, 휴대폰을 테이블에 내려놓고 연구자의 안내를 기다려주세요.'
